### ISSUE TITLE
SessionTimeoutState.userInactivityTimeout event keep calling even when user is interact with the app .

### ISSUE THREAD

**Issue by anil-softuvo1** [SankethBK/local_session_timeout#15]

**Comment by anil-softuvo1** [comment]
SessionTimeoutState.userInactivityTimeout event keep calling even when user is interact with the app. 

I have implemented the code on home screen , when i'm on home screen and home screen is idle for 10 seconds then this works fine . but when i'm on other screen and keep interacting with the app it sends back me to pin screen . Here is my code 

handleLocalSession(seconds: 10);


handleLocalSession({int? seconds}) {
    sessionConfig = SessionConfig(
        invalidateSessionForAppLostFocus: Duration(seconds: seconds!),
        invalidateSessionForUserInactivity: Duration(seconds: seconds));

    sessionConfig.stream.listen((SessionTimeoutState timeoutEvent) {
      sessionStateStream.add(SessionState.stopListening);
      if (timeoutEvent == SessionTimeoutState.userInactivityTimeout) {
        // handle user  inactive timeout
        log("userInactivityTimeout ");
        Get.toNamed(PageRoutes.pinScreen);
      } else if (timeoutEvent == SessionTimeoutState.appFocusTimeout) {
        // handle user  app lost focus timeout
        log("appFocusTimeout  ");
        Get.toNamed(PageRoutes.pinScreen);
      }
    });
  }

**Comment by SankethBK** [comment]
Default value of `userActivityDebounceDuration` is 10 seconds which means it records only one user event for 10 seconds (to prevent memory leaks because of setTimeout objects), you can change this value to a lower number like 1 or 2 seconds. You can pass it as a parameter to SessionTimeoutManager
