### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by blacknight9** [SankethBK/local_session_timeout#18]
Hey,

i really like this package, it does  what i need, but one thing is missing, is when user deletes the app .

my app has rooms, and i use the package to kick user out after being inactive  for x amount of time.

but if user deletes the app then the user will not be kicked .

i hope you consider adding this to the package 

thank you

**Comment by SankethBK** [comment]
Hi, 

It is possible to implement emission of timeout events when the app is suddenly closed / deleted by overrriding the `dispose` method in lifecycle methods of `SessionTimeoutManager`. But its not guaranteed to be called always called if the app is forcefully closed by the operating system or if the device is turned off while the app is running, 

Can you please verify if dispose method gets called most of the times when your app is deleted while its running?
