### ISSUE TITLE
    sessionStateStream.add(SessionState.startListening); causes screen navigation issues

### ISSUE THREAD

**Issue by moses-sichone** [SankethBK/local_session_timeout#19]
When sessionStateStream is used and SessionState.startListening is added, this causes issues with navigating to the next screen or with the current screen

Version: local_session_timeout: ^2.3.0

**Comment by SankethBK** [comment]
Hi, can you please more details on what are the issues you are facing, if possible also include code snippets for reproducing the issue

**Comment by moses-sichone** [comment]
Hi sorry, the issue was when i tried to initialize sessionStateStream and listen to its changes globally via the provider class.
It seems this was causing issues and popping whichever screen I try to navigate to when I add SessionState.startListening.
Followed the normal implementation and didn't face any issues after.

**Comment by DavidOrakpo** [comment]
I'm also facing this issue. Can you give details on how you went about solving it?

**Comment by moses-sichone** [comment]
> I'm also facing this issue. Can you give details on how you went about solving it?

Where are you facing this issue in your app?
And where have you initialized the session?
