### ISSUE TITLE
Upgrading to Flutter 3.0 shows warning

### ISSUE THREAD

**Issue by officiallx** [SankethBK/local_session_timeout#2]
**Error Message** 
/D:/flutter_windows_3.0.3-stable/.pub-cache/hosted/pub.dartlang.org/local_session_timeout-0.2.0/lib/src/session_timeout_manager.dart:35:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter_windows_3.0.3-stable/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance?.addObserver(this);

Because of this warning, when session timeout has ended it is not navigating to Login Page.

**Comment by SankethBK** [comment]
@officiallx thank you for reporting the issue. I will look into it

**Comment by SankethBK** [comment]
Have fixed it in version 2.0.0
