### ISSUE TITLE
Session manager times out on auth screen

### ISSUE THREAD

**Issue by ikennaumeh** [SankethBK/local_session_timeout#22]
Session manager still times out on auth screen even after i stop listening or havent started listerning at all. 
ie. I start listening after login button is clicked.

i use the sample code presented in pub.dev

```
 final sessionConfig = SessionConfig(
      invalidateSessionForAppLostFocus: const Duration(seconds: 30),
      invalidateSessionForUserInactivity: const Duration(minutes: 1),
    );
    sessionConfig.stream.listen((SessionTimeoutState timeoutEvent) {
      // stop listening, as user will already be in login page
      appModel?.sessionStateStream.add(SessionState.stopListening);

      if (timeoutEvent == SessionTimeoutState.userInactivityTimeout) {
        appModel?.handleTimeoutAndLogin();
      } else if (timeoutEvent == SessionTimeoutState.appFocusTimeout) {
        appModel?.handleTimeoutAndLogin();
      }
    });  
```

and i dont start listening till i click the button on login. I dont understand why then it times out on login/auth screen

**Comment by SankethBK** [comment]
Hi @ikennaumeh , can you please post the code snippet where you are initialising SessionTimeoutManager

**Comment by ikennaumeh** [comment]
Here @SankethBK : SessionTimeoutManager(
        userActivityDebounceDuration: const Duration(seconds: 10),
        sessionConfig: sessionConfig,
        sessionStateStream: appModel?.sessionStateStream.stream,
        child: MaterialApp())

**Comment by SankethBK** [comment]
Hey sorry i missed this, the issue in above code is `userActivityDebounceDuration` is very high, try reducing it to 1 second
