### ISSUE TITLE
Warning alert with timer reducing before logout 

### ISSUE THREAD

**Issue by vikramaggarwal13** [SankethBK/local_session_timeout#28]
Right now current features are working fine whatever is implemented in this plugin. But one more feature should be included in this  

Requirement is : 

Prior to logging out at the designated time, it is our intention to display an alert containing relevant content. This alert will offer the user the option to "remain signed in."

**Comment by SankethBK** [comment]
@vikramaggarwal13 this library only emits events. It's up to your application how you want to handle these events. In your case when a logout event is emitted, instead of actually logging out user you can display an alert to stay logged in.

**Comment by vikramaggarwal13** [comment]
@SankethBK Certainly. We have implemented an alert with two buttons, "Stay Signed In" and "Logout," which is displayed at the specified time. In the event that a user does not take any action on the alert, we are seeking a solution to automatically log them out after a few minutes using this plugin.

**Comment by vikramaggarwal13** [comment]
@SankethBK Can we have remaining time value in seconds ? as before 15 seconds of logout we want to show some alert.

**Comment by SankethBK** [comment]
yes, it takes a `Duration` object, you can pass `Duration(seconds: 15)`

**Comment by vikramaggarwal13** [comment]
```
 SessionConfig(
        invalidateSessionForAppLostFocus: const Duration(minutes: 10),
        invalidateSessionForUserInactivity: const Duration(minutes: 10))
```
        
  I have passed 10 minutes . I want to show alert after 8 minutes and after 10 minutes logout. 
  I need to access remaining duration into some variable based on which i can put some condition to show alert. 
If there is some quick communication mechanism then we can connect so that i can clear my doubt in once. 

My mail id is vikramaggarwal13@gmail.com

**Comment by SankethBK** [comment]
Hi this can be solved by passing 8 minutes in `SessionConfig`

```
 SessionConfig(
        invalidateSessionForAppLostFocus: const Duration(minutes: 8),
        invalidateSessionForUserInactivity: const Duration(minutes: 8))
```

when you receive the logout event, instead of logging out start a new timer within your app for 2 minutes, after which you'll actually log out the user

**Comment by vikramaggarwal13** [comment]
@SankethBK Yes I have used below code to control my situation 

```
final sessionConfig = SessionConfig(
        invalidateSessionForAppLostFocus: const Duration(minutes: 20),
        invalidateSessionForUserInactivity: const Duration(minutes: 20));
    final sessionConfig_new = SessionConfig(
        invalidateSessionForAppLostFocus: const Duration(minutes: 10),
        invalidateSessionForUserInactivity: const Duration(minutes: 10));

.................................................................
return SessionTimeoutManager(
      sessionConfig: sessionConfig_new,
      userActivityDebounceDuration: const Duration(seconds: 10),
      child: SessionTimeoutManager(
        sessionConfig: sessionConfig,
        userActivityDebounceDuration: const Duration(seconds: 10),
        child: GetMaterialApp(
..........................

```
Thanks above code solved my problem.
