### ISSUE TITLE
Reset inactivity on textfield

### ISSUE THREAD

**Issue by wfsiew** [SankethBK/local_session_timeout#3]
How to reset inactivity when editing textfield ?

**Comment by SankethBK** [comment]
Hi @wfsiew  can you please elaborate your issue

**Comment by wfsiew** [comment]
Currently how does it reset the inactivity timeout when user tap something on ui? What if user start to type something into a text field input, does it reset the inactivity timer?

**Comment by SankethBK** [comment]
Currently it is based only on click events. I see you got a good point, a temporary solution might be just to increase the value of userInactvitiyTimeout. So that user can click somewhere in that meantime

**Comment by SankethBK** [comment]
I will add a method to disable the timer if the soft keyboard is open

**Comment by SankethBK** [comment]
The issue has been addressed in release [1.0.0](https://github.com/SankethBK/local_session_timeout/releases/tag/1.0.0)
