### ISSUE TITLE
Not working on desktop

### ISSUE THREAD

**Issue by oliverbytes** [SankethBK/local_session_timeout#4]
Can anyone else confirm? I believe flutter still doesn't support lifecycle on desktop and I can see the source of this using the built in lifecycle feature.

**Comment by SankethBK** [comment]
Are you referring to user inactivity timeout or timeout when app is in background? User inactivity timeout should work on every platform, I'll confirm about other

**Comment by SankethBK** [comment]
Have updated the same in the package's description to prevent misunderstanding. Please re-open if necesary.
